### ISSUE TITLE
Ignore OneNote Notebooks

### ISSUE THREAD

**Issue by Modelmat** [cjnaz/rclonesync-V2#13]
Similar to with Google docs & https://github.com/ncw/rclone/issues/211 can we ignore onenote notebooks?

**Comment by cjnaz** [comment]
My read of the #211 thread is that rclone doesn't have any special handling for Onedrive document files, and that ncw doesn't know what to code.
Are documents created on Onedrive with Office365 saved in a special format?
If the files are just normal files then you can add them in your filters file so that they are not synch'd by adding `- *.one` and `- *.onetoc2` for your specific case for Onenote files.  Is that sufficient?

**Comment by Modelmat** [comment]
Yes, it is sufficient for me (I have everything in one Notebook directory) but it would be nice to be able to not have to do an exclusion filter for this.

**Comment by cjnaz** [comment]
I don't think it is appropriate to hard code or to add switches for specific file types.   Google docs are an exception since these files cannot be handled as normal files.
