### ISSUE TITLE
--dry-run doesn't record actions

### ISSUE THREAD

**Issue by erakli** [cjnaz/rclonesync-V2#17]
If we try to do `--first-run` and `--dry-run` in case when there are new files in cloud (for instance), we'll get proper try to copy new files in local

```
2019-01-13 13:34:28,615:    Path2      --first-sync copying to Path1     - .../Clouds/Yandex.Disk/Поездки/2018/декабрь/литва/документы/finnair (юля).pdf
2019/01/13 13:34:29 INFO  : Local file system at .../Clouds/Yandex.Disk/Поездки/2018/декабрь/литва/документы: Modify window is 1ns
2019/01/13 13:34:29 NOTICE: finnair (юля).pdf: Not copying as --dry-run
2019/01/13 13:34:29 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        1.1s
```

But then, we get messages like the next one (notice, that paths are same, despite they are in Russian)
```
2019/01/13 13:35:52 NOTICE: Поездки/2018/декабрь/литва/документы/finnair (юля).pdf: Not deleting as --dry-run
```

There should be some sort of recording, because it looks inconsistent.

**Comment by cjnaz** [comment]
Thanks @erakli,
The messaging is inconsistent because the transfer to Path1 is done with individual rclone copy and delete commands for every different file on Path2, while the final transaction to make Path2 look like Path1 is done with a single rlcone sync command.
See issue #8 for more insight on the process flow.  (Note that the new proposed process flow has **not** been implemented yet - it is not in V2.2 and newer.  I'll update the issue to clarify.)  Since the current final operation is an rclone sync the messages will remain inconsistent. 
Also, check out the `--dry-run oddity` note in the README.md.  
I propose to close this issue, agreed?
