### ISSUE TITLE
Make Path1 and Path2 named arguments

### ISSUE THREAD

**Issue by 3ter** [cjnaz/rclonesync-V2#48]
I'd propose to change the argument parsing for `Path1` and `Path2`:
In the case of `first-sync` at least one of them should need to be marked with `--source` or something similar, to reduce confusion of what path actually "wins".

Thanks a lot for bringing that bidirectional rclone sync to live @cjnaz <3.

**Comment by cjnaz** [comment]
Thanks @3ter for the feedback and support..

As you may have already figured out, the not-executed-deletes in your original post are not real - they are an artifact of the --first-sync _and_ --dry-run.  See `--dry-run oddity` in the README.md.  

The net result of a --first-sync (without --dry-run) will always be the superset of both sides, with the only exception due to the finally executed `rclone sync Path1 Path2` if rclone itself detects a difference between the Path1 and Path2 versions of a file - Path1 always wins even if its the older file.  See `--first-sync` in the README.md.

So in actuality, there is no "source/destination" or "master/slave" dependency in --first-sync or normal (non --first-sync) modes.

I'll take the liberty of closing this issue, but your further comments are welcome.

**Comment by 3ter** [comment]
You've got it completely right, @cjnaz. Thanks for clarifying it up further!
