### ISSUE TITLE
Google Drive file revisions in LSL file - Warning Duplicate line in LSL file

### ISSUE THREAD

**Issue by maxtimbo** [cjnaz/rclonesync-V2#73]
I run rclonesync every few days via crontab. The output is sent to me via email. I don't think these warning are breaking anything, but I get like a novella's worth of the same warning: Duplicate line in LSL file, Prior found (keeping latest). Is there a way to cull these warnings without turning them off?

Here's the complete command I use in cron:

/root/rclonesync-v2/rclonesync -f /root/rclonesync/Filters /home/Programming Prod:/ --rclone-args --drive-skip-gdocs

**Comment by cjnaz** [comment]
Note that I suspect that the root cause for the duplicates is an rclone or Drive issue/bug.  I cannot reproduce it on my Drive account, so I need your help.  

I'm submitting an issue at rclone.  Please provide some supporting data:

- What rclone version are you running?
- What rclonesync version are you running?
- Confirm that you are using Google Drive.
- Please provide a grep of the Drive LSL file for one of the duplicates filenames.
- Overall, How many file duplicates are we talking about?
- For these files, do you have any insight on how the duplicate versions came to be? 
- Please post a the log output from rclonesync with --verbose.  Feel free to edit out a bunch of redundant duplicate file lines, and sanitize it.  If you would rather share offline, please post to your Gdrive and send me a link.

If the LSL file truly does have file revisions, then using the most recent seems to be the correct behavior for rclonesync.  You can eliminate all the duplicate warnings by commenting out the `logging.warning` lines 649 and 651 in rclonesync V3.2 (for now).

**Comment by cjnaz** [comment]
I see that you are using a filters file.  Please try `rclone lsl Prod:/ > <somefile>` with and without `--filter-from /root/rclonesync/Filters`, and check for the duplicate listed files.  

This will help isolate the problem by seeing if filtering has any affect.

**Comment by cjnaz** [comment]
@maxtimbo - ping

**Comment by cjnaz** [comment]
Please do:
- `rclone lsl Prod:/  |  grep one_of_the_duplicate_filenames  >  no_filter.txt`
- `rclone lsl Prod:/ --filter-from /root/rclonesync/Filters  |  grep one_of_the_duplicate_filenames  >  with_filter.txt`

If the dup shows up with our without the filter then the filter is not related to the problem.  Just need to confirm.

Please post the problem .txt file here, or upload to drive and share it with me at github@cjnaz.com.

There is a long history with duplicates on Drive, but I've not seen discussion of them showing up in LSLs.

**Comment by maxtimbo** [comment]
- `rclone lsl Prod:/ | grep one_of_the_duplicate_filenames > no_filter.txt`

      root@redacted:~/rclonesync-v2# cat ../no_filter.txt
         997317 2018-07-26 17:35:42.806000000 redacted/redacted/Spots/mystique new.mp3
         997317 2018-07-26 17:23:42.476000000 redacted/redacted/Spots/mystique new.mp3

- `rclone lsl Prod:/ --filter-from /root/rclonesync/Filters | grep one_of_the_duplicate_filenames > with_filter.txt`

      root@redacted:~/rclonesync-v2# cat ../with_filter.txt
         997317 2018-07-26 17:35:42.806000000 redacted/redacted/Spots/mystique new.mp3
         997317 2018-07-26 17:23:42.476000000 redacted/redacted/Spots/mystique new.mp3

I started doing some tests. I have to run with `--exclude` to avoid some subdirectories as they contain some redundant/very large files.

**Comment by cjnaz** [comment]
rclone.org posted issue...
[https://forum.rclone.org/t/drive-duplicate-files-reported-by-rclone-lsl/23045](https://forum.rclone.org/t/drive-duplicate-files-reported-by-rclone-lsl/23045)

**Comment by cjnaz** [comment]
So it seems that the Google Drive duplicates are not important files and can be purged.  You should be able to see them on the Drive web interface.  You can manually delete them via the web interface, or consider using the rclone dedupe command.

I think its best for the user to clean up the rubble on Drive rather than taking out the warning messages from rclonesync.
